version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - ./deploy.sh coffee-store-ci-test #make deploy.sh executable before committing.
  post_build:
    commands:
      - STACK_NAME=coffee-store-ci-test npm run test